export const LOGIN_ACTION = 'LOGIN_ACTION'
export const REGISTER_ACTION = 'REGISTER_ACTION'
export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN'

export const ADD_ADDRESS = 'ADD_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'
export const SAVE_ADDRESS = 'SAVE_ADDRESS'

export const SET_USER_PROFILE = 'SET_USER_PROFILE'